### PR TITLE
Set license to Apache-2.0 in package.json

### LINKED ISSUE #171: Missing license in package.json
https://github.com/aws/aws-sdk-js-crypto-helpers/blob/f53353a0af36fcaaa13fc06e808de9788cc41008/package.json#L22

Probably should replace this.  PR coming shortly.

### PR DESCRIPTION
**Pull request by justingrant**
Fixes #171.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by MatthewBennington** [comment]
Hi @justingrant, would you kindly update your branch now that #169 has been merged in?

**Comment by justingrant** [comment]
> Hi @justingrant, would you kindly update your branch now that #169 has been merged in?

Hi @MatthewBennington - The branch is now rebased onto the latest master branch. Let me know if there's anything else I can help with. Cheers.

**Review by lavaleri — APPROVED** [review]

**Comment by lavaleri** [comment]
Thank you for your contribution @justingrant !

**Comment by justingrant** [comment]
Thanks @lavaleri! Hey, would it be possible to get a release to npm soon? See #175 for details about why this is needed.

**Pull request merged**
