### PR TITLE
chore: switch to alpha releases of @aws-sdk packages

### PR DESCRIPTION
**Pull request by trivikr**
*Issue #, if available:*
Refs: https://github.com/aws/aws-sdk-js-crypto-helpers/issues/18

*Description of changes:*
* switch to alpha releases of @aws-sdk packages
* Will mark for review once alpha packages are released

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by trivikr** [comment]
This PR is ready to review

But I would like to set up TravisCI on this project first before merging this PR https://github.com/aws/aws-sdk-js-crypto-helpers/pull/21

**Comment by mattsb42-aws** [comment]
>  .github/workflows/ci-unit-tests.yaml Expected — Waiting for status to be reported 

Assuming this uses the same underlying thing as the badges, if a workflow has a name defined, it needs to be referenced by the name, not the filepath.

https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository

**Comment by trivikr** [comment]
@mattsb42-aws Any action item for me on this?

**Comment by mattsb42-aws** [comment]
> @mattsb42-aws Any action item for me on this?

No; that was meant as a message to @seebees. We just needed to change how the branch protection rules were set.

**Comment by trivikr** [comment]
@seebees Can you release alpha (or preview) versions of @aws-crypto packages with these dependencies?

**Pull request merged**
